[PHP]
memory_limit = 512M
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
expose_php = Off

[opcache]
; web běží přes `artisan serve` (CLI SAPI), proto enable_cli = 1
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
